# Generated by Django 2.2.28 on 2023-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bnfrh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vbcbc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbdbd', models.BigIntegerField()),
                ('cdde', models.BigIntegerField()),
            ],
        ),
    ]
