# Generated by Django 2.2.28 on 2023-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vbcbc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnfrh',
            name='cbcb',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
